### ISSUE TITLE
build failing

### ISSUE THREAD

**Issue by codebam** [SharzyL/pastebin-worker#15]
```
⬢[codebam@toolbox pastebin-worker]$ yarn
yarn install v1.22.18
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 5.99s.
⬢[codebam@toolbox pastebin-worker]$ yarn build
yarn run v1.22.18
$ webpack --mode=production
node:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:133:10)
    at BulkUpdateDecorator.hashFactory (/var/home/codebam/git/pastebin-worker/node_modules/webpack/lib/util/createHash.js:145:18)
    at BulkUpdateDecorator.update (/var/home/codebam/git/pastebin-worker/node_modules/webpack/lib/util/createHash.js:46:50)
    at RawSource.updateHash (/var/home/codebam/git/pastebin-worker/node_modules/webpack-sources/lib/RawSource.js:70:8)
    at NormalModule._initBuildHash (/var/home/codebam/git/pastebin-worker/node_modules/webpack/lib/NormalModule.js:880:17)
    at handleParseResult (/var/home/codebam/git/pastebin-worker/node_modules/webpack/lib/NormalModule.js:946:10)
    at /var/home/codebam/git/pastebin-worker/node_modules/webpack/lib/NormalModule.js:1038:4
    at processResult (/var/home/codebam/git/pastebin-worker/node_modules/webpack/lib/NormalModule.js:755:11)
    at /var/home/codebam/git/pastebin-worker/node_modules/webpack/lib/NormalModule.js:819:5 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.2.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by SharzyL** [comment]
Thank you for your feedback!

It should be a problem about the compatibility with node and OpenSSL. You may try solutions proposed in [the stackoverflow post](https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported). For example, `export NODE_OPTIONS=--openssl-legacy-provider` before running webpack build. Or you may downgrade your node.

In addition, could you provide the environment information (distro, versions of node, webpack and openssl) so I can try reproducing this issue?

**Comment by codebam** [comment]
Ah you're right it builds with `export NODE_OPTIONS=--openssl-legacy-provider`. This is my env. I'm on Fedora Silverblue building inside a toolbox.

```
SHELL=/bin/bash
COLORTERM=truecolor
NVM_INC=/var/home/codebam/.nvm/versions/node/v18.2.0/include/node
HISTCONTROL=ignoredups
XDG_MENU_PREFIX=gnome-
HISTSIZE=
HOSTNAME=toolbox
NODE_OPTIONS=--openssl-legacy-provider
SSH_AUTH_SOCK=/run/user/1000/gnupg/S.gpg-agent.ssh
DISTTAG=f36container
DESKTOP_SESSION=gnome
GPG_TTY=/dev/pts/1
EDITOR=vim
NAME=fedora-toolbox
PWD=/var/home/codebam/git/pastebin-worker
LOGNAME=codebam
XDG_SESSION_DESKTOP=gnome
XDG_SESSION_TYPE=wayland
TOOLBOX_PATH=/usr/bin/toolbox
MANPATH=/var/home/codebam/.nvm/versions/node/v18.2.0/share/man:/var/home/codebam/.npm-packages/share/man:/usr/share/man:/var/home/codebam/.local/share/man:/usr/local/share/man
XAUTHORITY=/run/user/1000/.mutter-Xwaylandauth.858XM1
FZF_DEFAULT_COMMAND=rg --files --no-ignore --hidden --follow --glob "!.git/*"
container=oci
HOME=/var/home/codebam
LANG=C.UTF-8
_JAVA_AWT_WM_NONREPARENTING=1
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=01;37;41:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.webp=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=01;36:*.au=01;36:*.flac=01;36:*.m4a=01;36:*.mid=01;36:*.midi=01;36:*.mka=01;36:*.mp3=01;36:*.mpc=01;36:*.ogg=01;36:*.ra=01;36:*.wav=01;36:*.oga=01;36:*.opus=01;36:*.spx=01;36:*.xspf=01;36:
XDG_CURRENT_DESKTOP=GNOME
FGC=f36
VTE_VERSION=6800
WAYLAND_DISPLAY=wayland-0
QT_QPA_PLATFORM=wayland
NVM_DIR=/var/home/codebam/.nvm
TERM=xterm-256color
LESSOPEN=||/usr/bin/lesspipe.sh %s
USER=codebam
DISPLAY=:0
SHLVL=1
NVM_CD_FLAGS=
MOZ_ENABLE_WAYLAND=1
PAGER=less
XDG_RUNTIME_DIR=/run/user/1000
NPM_PACKAGES=/var/home/codebam/.npm-packages
NODE_PATH=/var/home/codebam/.npm-packages/lib/node_modules:
DEBUGINFOD_URLS=https://debuginfod.fedoraproject.org/ 
which_declare=declare -f
KDEDIRS=/usr
XDG_DATA_DIRS=/var/home/codebam/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/
PATH=/var/home/codebam/.nvm/versions/node/v18.2.0/bin:/bin:/var/home/codebam/.npm-packages/bin:/var/home/codebam/.cargo/bin:/var/home/codebam/.cabal/bin:/var/home/codebam/.go/bin:/var/home/codebam/.gem/ruby:/var/home/codebam/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
VERSION=36
HISTFILESIZE=
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
FZF_DEFAULT_OPTS= --color=bg+:#3B4252,bg:#2E3440,spinner:#88C0D0,hl:#81A1C1 --color=fg:#D8DEE9,header:#81A1C1,info:#EBCB8B,pointer:#88C0D0 --color=marker:#88C0D0,fg+:#ECEFF4,prompt:#EBCB8B,hl+:#81A1C1
NVM_BIN=/var/home/codebam/.nvm/versions/node/v18.2.0/bin
MAIL=/var/spool/mail/codebam
GOPATH=/var/home/codebam/.go
BASH_FUNC_which%%=() {  ( alias;
 eval ${which_declare} ) | /usr/bin/which --tty-only --read-alias --read-functions --show-tilde --show-dot $@
}
_=/bin/env
```

**Comment by codebam** [comment]
So it builds but I couldn't get it to publish correctly. I had to modify the wrangler.toml for the newest wrangler.

```
name = "pb"
main = "dist/worker.js"

account_id = ""
workers_dev = true
compatibility_date = "2022-05-31"

kv_namespaces = [
  { binding = "PB", id = "76eaf94821494038af057d850690a6b2" },
]

[build]
command = "npm install && npm run build"
```
